# -*- coding: utf-8 -*-
"""Email Classifier Finalv2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18ZeWLTfgp8veViAO_PukK7RIGA-I2PHO
"""

# ============================================================
# COMPLETE PIPELINE — SINGLE CELL
# ============================================================

# Install dependencies first: pip install -r requirements.txt

import pandas as pd
import numpy as np
import re
import os
import warnings
import time
from sklearn.model_selection import (
    train_test_split, StratifiedKFold, cross_val_score
)
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.feature_selection import SelectKBest, chi2, f_classif, mutual_info_classif
from sklearn.metrics import (
    classification_report, accuracy_score, f1_score,
    precision_score, recall_score, confusion_matrix
)
from sklearn.ensemble import (
    RandomForestClassifier, ExtraTreesClassifier, VotingClassifier
)
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.decomposition import PCA
import xgboost as xgb
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, TensorDataset
from opacus import PrivacyEngine
from opacus.validators import ModuleValidator
import matplotlib.pyplot as plt
import seaborn as sns
from matplotlib.patches import Patch
warnings.filterwarnings('ignore')

CONFIG = {
    'test_size': 0.2, 'random_state': 42,
    'tfidf_max_features': 5000, 'tfidf_ngram_range': (1, 2),
    'tfidf_min_df': 3, 'tfidf_max_df': 0.95, 'select_k': 3000,
    'et_n_estimators': 500, 'rf_n_estimators': 500, 'rf_max_depth': 25,
    'xgb_n_estimators': 300, 'xgb_max_depth': 8, 'xgb_lr': 0.05,
    'xgb_subsample': 0.8, 'xgb_colsample': 0.8, 'cv_folds': 5,
}
label_names = {0: 'Ham', 1: 'Spam', 2: 'Phishing'}
print("✅ Ready\n")

# ============================================================
# STEP 1: LOAD DATA
# ============================================================
print("=" * 70)
print("STEP 1: LOAD DATA")
print("=" * 70)

BASE_DIR = os.environ.get('EMAIL_CLASSIFIER_DATA_DIR', './data')
filepath = os.path.join(BASE_DIR, 'processed_data', 'final_dataset.csv')
assert os.path.exists(filepath), (
    f"Not found: {filepath}. Place your dataset there, or set the "
    f"EMAIL_CLASSIFIER_DATA_DIR environment variable to its location."
)

df = pd.read_csv(filepath)
df['subject'] = df['subject'].fillna('').astype(str)
df['body'] = df['body'].fillna('').astype(str)
df['text'] = (df['subject'].str.strip() + ' ' + df['body'].str.strip()).str.strip()
df = df[df['text'].str.len() > 0].reset_index(drop=True)

print(f"✅ Loaded {len(df)} emails")
for label in sorted(df['label'].unique()):
    count = len(df[df['label'] == label])
    print(f"   {label_names[label]}: {count} ({count/len(df)*100:.1f}%)")

# ============================================================
# STEP 2: FEATURE EXTRACTION
# ============================================================
print(f"\n{'='*70}")
print("STEP 2: FEATURE EXTRACTION")
print("=" * 70)


class EmailFeatureExtractor:
    def __init__(self):
        self.phishing_keywords = [
            'verify', 'account', 'bank', 'password', 'confirm', 'login',
            'click', 'update', 'suspend', 'secure', 'unauthorized',
            'credential', 'identity', 'expire', 'immediately', 'validate',
            'ssn', 'social security', 'reset', 'locked', 'unusual activity',
            'compromised', 'sign in', 'log in', 'security alert', 'deactivate'
        ]
        self.spam_keywords = [
            'free', 'winner', 'congratulations', 'prize', 'offer', 'discount',
            'buy', 'cheap', 'deal', 'limited', 'subscribe', 'unsubscribe',
            'cash', 'money', 'earn', 'income', 'million', 'dollars', 'credit',
            'guarantee', 'no cost', 'risk free', 'order now', 'lowest price',
            'save big', 'act now', 'apply now', 'call now'
        ]
        self.urgency_keywords = [
            'urgent', 'immediately', 'action required', 'act now',
            'limited time', 'expire', 'deadline', 'asap', 'hurry',
            'warning', 'alert', 'important', 'attention', 'notice',
            'final notice', 'last chance', "don't delay"
        ]

    def _count_keywords(self, text, keyword_list):
        text_lower = text.lower()
        return sum(1 for kw in keyword_list if kw in text_lower)

    def _extract_urls(self, text):
        return re.findall(r'https?://[^\s<>"]*|www\.[^\s<>"]*', text)

    def extract_subject_features(self, subject):
        s = str(subject)
        f = {}
        f['sub_length'] = len(s)
        f['sub_word_count'] = len(s.split())
        f['sub_has_exclamation'] = 1 if '!' in s else 0
        f['sub_exclamation_count'] = s.count('!')
        f['sub_has_question'] = 1 if '?' in s else 0
        f['sub_has_dollar'] = 1 if '$' in s else 0
        f['sub_uppercase_ratio'] = sum(1 for c in s if c.isupper()) / max(len(s), 1)
        f['sub_special_char_count'] = sum(
            1 for c in s if not c.isalnum() and not c.isspace()
        )
        f['sub_phishing_kw'] = self._count_keywords(s, self.phishing_keywords)
        f['sub_spam_kw'] = self._count_keywords(s, self.spam_keywords)
        f['sub_urgency_kw'] = self._count_keywords(s, self.urgency_keywords)
        f['sub_has_re_fwd'] = 1 if re.search(r'^(re|fw|fwd):', s, re.I) else 0
        f['sub_all_caps'] = 1 if s == s.upper() and len(s) > 3 else 0
        f['sub_starts_with_urgent'] = 1 if re.search(
            r'^(urgent|important|alert|warning|attention)', s, re.I
        ) else 0
        f['sub_has_number'] = 1 if re.search(r'\d', s) else 0
        return f

    def extract_body_features(self, body):
        b = str(body)
        f = {}
        f['body_length'] = len(b)
        words = b.split()
        f['body_word_count'] = len(words)
        f['body_avg_word_length'] = np.mean([len(w) for w in words]) if words else 0
        f['body_sentence_count'] = b.count('.') + b.count('!') + b.count('?')
        f['body_paragraph_count'] = b.count('\n\n') + 1
        urls = self._extract_urls(b)
        f['body_url_count'] = len(urls)
        f['body_has_url'] = 1 if urls else 0
        f['body_has_ip_in_url'] = 0
        for u in urls:
            if re.search(r'\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}', u):
                f['body_has_ip_in_url'] = 1
                break
        f['body_dot_count_urls'] = sum(u.count('.') for u in urls)
        if urls:
            ul = [len(u) for u in urls]
            f['body_url_avg_length'] = np.mean(ul)
            f['body_url_max_length'] = max(ul)
        else:
            f['body_url_avg_length'] = 0
            f['body_url_max_length'] = 0
        f['body_has_html'] = 1 if re.search(r'<[a-zA-Z][^>]*>', b) else 0
        f['body_img_tag_count'] = len(re.findall(r'<img[\s>]', b, re.I))
        f['body_script_tag_count'] = len(re.findall(r'<script[\s>]', b, re.I))
        f['body_style_tag_count'] = len(re.findall(r'<style[\s>]', b, re.I))
        f['body_anchor_tag_count'] = len(re.findall(r'<a[\s>]', b, re.I))
        f['body_iframe_tag_count'] = len(re.findall(r'<iframe[\s>]', b, re.I))
        f['body_has_form'] = 1 if re.search(r'<form', b, re.I) else 0
        if len(b) > 0:
            f['body_special_char_ratio'] = sum(
                1 for c in b if not c.isalnum() and not c.isspace()
            ) / len(b)
            alpha = [c for c in b if c.isalpha()]
            f['body_uppercase_ratio'] = (
                sum(1 for c in alpha if c.isupper()) / len(alpha) if alpha else 0
            )
            f['body_digit_ratio'] = sum(1 for c in b if c.isdigit()) / len(b)
        else:
            f['body_special_char_ratio'] = 0
            f['body_uppercase_ratio'] = 0
            f['body_digit_ratio'] = 0
        f['body_exclamation_count'] = b.count('!')
        f['body_question_count'] = b.count('?')
        f['body_dollar_count'] = b.count('$')
        f['body_email_count'] = len(re.findall(
            r'[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}', b
        ))
        f['body_phone_count'] = len(re.findall(
            r'\b\d{3}[-.]?\d{3}[-.]?\d{4}\b', b
        ))
        f['body_phishing_kw_count'] = self._count_keywords(b, self.phishing_keywords)
        f['body_spam_kw_count'] = self._count_keywords(b, self.spam_keywords)
        f['body_urgency_kw_count'] = self._count_keywords(b, self.urgency_keywords)
        wc = max(f['body_word_count'], 1)
        f['body_phishing_kw_density'] = f['body_phishing_kw_count'] / wc
        f['body_spam_kw_density'] = f['body_spam_kw_count'] / wc
        f['body_urgency_kw_density'] = f['body_urgency_kw_count'] / wc
        f['body_total_suspicious_kw'] = (
            f['body_phishing_kw_count'] + f['body_spam_kw_count'] +
            f['body_urgency_kw_count']
        )
        return f

    def extract_combined_features(self, subject, body):
        f = {}
        text = str(subject) + ' ' + str(body)
        f['total_length'] = len(text)
        f['total_word_count'] = len(text.split())
        f['total_url_count'] = len(self._extract_urls(text))
        f['total_phishing_kw'] = self._count_keywords(text, self.phishing_keywords)
        f['total_spam_kw'] = self._count_keywords(text, self.spam_keywords)
        f['total_urgency_kw'] = self._count_keywords(text, self.urgency_keywords)
        sub_len = max(len(str(subject)), 1)
        body_len = max(len(str(body)), 1)
        f['subject_body_length_ratio'] = sub_len / (sub_len + body_len)
        f['kw_in_subject_not_body'] = 1 if (
            self._count_keywords(str(subject), self.phishing_keywords) > 0 and
            self._count_keywords(str(body), self.phishing_keywords) == 0
        ) else 0
        return f

    def extract_all(self, subject, body):
        features = {}
        features.update(self.extract_subject_features(subject))
        features.update(self.extract_body_features(body))
        features.update(self.extract_combined_features(subject, body))
        return features

    def extract_batch(self, subjects, bodies):
        all_features = []
        total = len(subjects)
        for i in range(total):
            if (i + 1) % 10000 == 0:
                print(f"   {i+1}/{total}")
            all_features.append(self.extract_all(subjects[i], bodies[i]))
        print(f"   {total}/{total} done")
        return pd.DataFrame(all_features)


start_time = time.time()
extractor = EmailFeatureExtractor()
feature_df = extractor.extract_batch(df['subject'].values, df['body'].values)
print(f"✅ {feature_df.shape[1]} features in {time.time()-start_time:.0f}s")

# ============================================================
# STEP 3: SPLIT + BASELINE
# ============================================================
print(f"\n{'='*70}")
print("STEP 3: SPLIT + BASELINE")
print("=" * 70)

y = df['label'].values
feature_names = feature_df.columns.tolist()
indices = np.arange(len(df))
train_idx, test_idx = train_test_split(
    indices, test_size=CONFIG['test_size'],
    random_state=CONFIG['random_state'], stratify=y
)
y_train = y[train_idx]
y_test = y[test_idx]

scaler_base = StandardScaler()
X_train_base = scaler_base.fit_transform(feature_df.values[train_idx])
X_test_base = scaler_base.transform(feature_df.values[test_idx])

model_all = ExtraTreesClassifier(
    n_estimators=CONFIG['et_n_estimators'],
    random_state=CONFIG['random_state'], n_jobs=-1
)
model_all.fit(X_train_base, y_train)
y_pred_all = model_all.predict(X_test_base)
acc_all = accuracy_score(y_test, y_pred_all)
f1_all = f1_score(y_test, y_pred_all, average='macro')
print(f"✅ Baseline: Acc={acc_all:.4f} | F1={f1_all:.4f}")
print(classification_report(y_test, y_pred_all,
                            target_names=['Ham', 'Spam', 'Phishing']))

# ============================================================
# STEP 4: FEATURE RANKING
# ============================================================
print(f"{'='*70}")
print("STEP 4: FEATURE RANKING (training only)")
print("=" * 70)

importances = model_all.feature_importances_
X_train_nonneg = X_train_base - X_train_base.min(axis=0)
chi2_scores, _ = chi2(X_train_nonneg, y_train)
mi_scores = mutual_info_classif(X_train_base, y_train,
                                 random_state=CONFIG['random_state'])
f_scores, _ = f_classif(X_train_base, y_train)

rank_df = pd.DataFrame({'feature': feature_names})
rank_df['chi2'] = chi2_scores
rank_df['mi'] = mi_scores
rank_df['anova'] = f_scores
rank_df['imp'] = importances

for col in ['chi2', 'mi', 'anova', 'imp']:
    rank_df[col + '_n'] = MinMaxScaler().fit_transform(rank_df[[col]])

rank_df['combined'] = (
    rank_df['chi2_n'] + rank_df['mi_n'] +
    rank_df['anova_n'] + rank_df['imp_n']
) / 4
rank_df = rank_df.sort_values('combined', ascending=False)

print("Top 15 features:")
for _, row in rank_df.head(15).iterrows():
    print(f"   {row['feature']:>35}: {row['combined']:.3f}")

# ============================================================
# STEP 5: TF-IDF + COMBINE (NO LEAKAGE)
# ============================================================
print(f"\n{'='*70}")
print("STEP 5: TF-IDF + COMBINE (leakage-free)")
print("=" * 70)


def clean_text(text):
    text = str(text).lower()
    text = re.sub(r'<[^>]+>', ' ', text)
    text = re.sub(r'https?://\S+|www\.\S+', 'URL', text)
    text = re.sub(r'\S+@\S+', 'EMAIL', text)
    text = re.sub(r'[^a-zA-Z0-9\s]', ' ', text)
    text = re.sub(r'\s+', ' ', text).strip()
    return text


df['clean_text'] = df['text'].apply(clean_text)
train_texts = df['clean_text'].values[train_idx]
test_texts = df['clean_text'].values[test_idx]

tfidf = TfidfVectorizer(
    max_features=CONFIG['tfidf_max_features'],
    ngram_range=CONFIG['tfidf_ngram_range'],
    min_df=CONFIG['tfidf_min_df'],
    max_df=CONFIG['tfidf_max_df'],
    sublinear_tf=True, stop_words='english'
)
tfidf_train = tfidf.fit_transform(train_texts).toarray()
tfidf_test = tfidf.transform(test_texts).toarray()

good_cols = [c for c in feature_df.columns
             if feature_df.iloc[train_idx][c].std() > 0]
scaler_hc = StandardScaler()
X_hc_train = scaler_hc.fit_transform(feature_df[good_cols].values[train_idx])
X_hc_test = scaler_hc.transform(feature_df[good_cols].values[test_idx])

X_train_combined = np.hstack([X_hc_train, tfidf_train])
X_test_combined = np.hstack([X_hc_test, tfidf_test])

k_select = min(CONFIG['select_k'], X_train_combined.shape[1])
selector = SelectKBest(f_classif, k=k_select)
X_train = selector.fit_transform(X_train_combined, y_train)
X_test = selector.transform(X_test_combined)

print(f"✅ Train: {X_train.shape} | Test: {X_test.shape}")
print(f"✅ NO LEAKAGE — all fitted on training data only")

# ============================================================
# STEP 6: SINGLE-LAYER MODELS
# ============================================================
print(f"\n{'='*70}")
print("STEP 6: SINGLE-LAYER MODELS")
print("=" * 70)

sl_models = {
    'ExtraTrees': ExtraTreesClassifier(
        n_estimators=CONFIG['et_n_estimators'],
        random_state=CONFIG['random_state'], n_jobs=-1),
    'XGBoost': xgb.XGBClassifier(
        n_estimators=CONFIG['xgb_n_estimators'],
        max_depth=CONFIG['xgb_max_depth'],
        learning_rate=CONFIG['xgb_lr'],
        subsample=CONFIG['xgb_subsample'],
        colsample_bytree=CONFIG['xgb_colsample'],
        use_label_encoder=False, eval_metric='mlogloss',
        random_state=CONFIG['random_state'], n_jobs=-1,
        tree_method='hist'),
    'RandomForest': RandomForestClassifier(
        n_estimators=CONFIG['rf_n_estimators'],
        max_depth=CONFIG['rf_max_depth'],
        random_state=CONFIG['random_state'], n_jobs=-1),
}

sl_results = {}
for name, model in sl_models.items():
    start = time.time()
    print(f"  {name}...", end=" ")
    model.fit(X_train, y_train)
    yp = model.predict(X_test)
    elapsed = time.time() - start
    acc = accuracy_score(y_test, yp)
    f1 = f1_score(y_test, yp, average='macro')
    sl_results[name] = {'accuracy': acc, 'f1': f1, 'predictions': yp}
    print(f"✅ {elapsed:.0f}s | Acc={acc:.4f} | F1={f1:.4f}")

# Fast ensemble
print(f"  Ensemble (fast)...", end=" ")
proba_et = sl_models['ExtraTrees'].predict_proba(X_test)
proba_xgb = sl_models['XGBoost'].predict_proba(X_test)
proba_rf = sl_models['RandomForest'].predict_proba(X_test)
y_pred_ens = np.argmax((proba_et + proba_xgb + proba_rf) / 3.0, axis=1)
acc_ens = accuracy_score(y_test, y_pred_ens)
f1_ens = f1_score(y_test, y_pred_ens, average='macro')
sl_results['Ensemble'] = {
    'accuracy': acc_ens, 'f1': f1_ens, 'predictions': y_pred_ens
}
print(f"✅ Acc={acc_ens:.4f} | F1={f1_ens:.4f}")

# ============================================================
# STEP 7: DUAL-LAYER MODELS
# ============================================================
print(f"\n{'='*70}")
print("STEP 7: DUAL-LAYER MODELS")
print("=" * 70)


class DualLayerClassifier:
    def __init__(self, l1, l2, verbose=True):
        self.l1, self.l2, self.verbose = l1, l2, verbose

    def fit(self, X, y):
        y1 = np.where(y == 2, 1, 0)
        if self.verbose:
            print(f"    L1: Phishing={np.sum(y1==1)}, Hybrid={np.sum(y1==0)}")
        self.l1.fit(X, y1)
        mask = (y != 2)
        if self.verbose:
            print(f"    L2: Ham={np.sum(y[mask]==0)}, Spam={np.sum(y[mask]==1)}")
        self.l2.fit(X[mask], y[mask])
        return self

    def predict(self, X):
        final = np.zeros(len(X), dtype=int)
        p1 = self.l1.predict(X)
        final[p1 == 1] = 2
        h = (p1 == 0)
        if np.any(h):
            final[h] = self.l2.predict(X[h])
        return final


def make_binary_xgb():
    return xgb.XGBClassifier(
        n_estimators=CONFIG['xgb_n_estimators'],
        max_depth=CONFIG['xgb_max_depth'],
        learning_rate=CONFIG['xgb_lr'],
        subsample=CONFIG['xgb_subsample'],
        colsample_bytree=CONFIG['xgb_colsample'],
        use_label_encoder=False, eval_metric='logloss',
        random_state=CONFIG['random_state'], n_jobs=-1,
        tree_method='hist')


dl_configs = {
    'DL-ExtraTrees': (
        ExtraTreesClassifier(n_estimators=CONFIG['et_n_estimators'],
                             random_state=CONFIG['random_state'], n_jobs=-1),
        ExtraTreesClassifier(n_estimators=CONFIG['et_n_estimators'],
                             random_state=CONFIG['random_state'], n_jobs=-1)),
    'DL-XGBoost': (make_binary_xgb(), make_binary_xgb()),
    'DL-RandomForest': (
        RandomForestClassifier(n_estimators=CONFIG['rf_n_estimators'],
                               max_depth=CONFIG['rf_max_depth'],
                               random_state=CONFIG['random_state'], n_jobs=-1),
        RandomForestClassifier(n_estimators=CONFIG['rf_n_estimators'],
                               max_depth=CONFIG['rf_max_depth'],
                               random_state=CONFIG['random_state'], n_jobs=-1)),
    'DL-Mixed': (
        ExtraTreesClassifier(n_estimators=CONFIG['et_n_estimators'],
                             random_state=CONFIG['random_state'], n_jobs=-1),
        make_binary_xgb()),
}

dl_results = {}
for name, (l1, l2) in dl_configs.items():
    start = time.time()
    print(f"\n  ── {name} ──")
    dl = DualLayerClassifier(l1, l2)
    dl.fit(X_train, y_train)
    yp = dl.predict(X_test)
    elapsed = time.time() - start
    acc = accuracy_score(y_test, yp)
    f1 = f1_score(y_test, yp, average='macro')
    dl_results[name] = {'accuracy': acc, 'f1': f1, 'predictions': yp}
    print(f"  ✅ {elapsed:.0f}s | Acc={acc:.4f} | F1={f1:.4f}")

# DL-Ensemble
print(f"\n  ── DL-Ensemble ──")
ens_l1 = VotingClassifier(estimators=[
    ('et', ExtraTreesClassifier(n_estimators=200,
                                random_state=42, n_jobs=-1)),
    ('xgb', make_binary_xgb()),
    ('rf', RandomForestClassifier(n_estimators=200,
                                  random_state=42, n_jobs=-1)),
], voting='soft', n_jobs=1)
ens_l2 = VotingClassifier(estimators=[
    ('et', ExtraTreesClassifier(n_estimators=200,
                                random_state=42, n_jobs=-1)),
    ('xgb', make_binary_xgb()),
    ('rf', RandomForestClassifier(n_estimators=200,
                                  random_state=42, n_jobs=-1)),
], voting='soft', n_jobs=1)

dl_ens = DualLayerClassifier(ens_l1, ens_l2)
dl_ens.fit(X_train, y_train)
yp = dl_ens.predict(X_test)
acc = accuracy_score(y_test, yp)
f1 = f1_score(y_test, yp, average='macro')
dl_results['DL-Ensemble'] = {'accuracy': acc, 'f1': f1, 'predictions': yp}
print(f"  ✅ Acc={acc:.4f} | F1={f1:.4f}")

# DL-ANN
print(f"\n  ── DL-ANN ──")


class EmailANN(nn.Module):
    def __init__(self, dim, out, drop=0.3):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(dim, 1024), nn.BatchNorm1d(1024),
            nn.LeakyReLU(0.1), nn.Dropout(drop),
            nn.Linear(1024, 512), nn.BatchNorm1d(512),
            nn.LeakyReLU(0.1), nn.Dropout(drop),
            nn.Linear(512, 256), nn.BatchNorm1d(256),
            nn.LeakyReLU(0.1), nn.Dropout(drop * 0.7),
            nn.Linear(256, 128), nn.BatchNorm1d(128),
            nn.LeakyReLU(0.1), nn.Dropout(drop * 0.5),
            nn.Linear(128, out))

    def forward(self, x):
        return self.net(x)


def train_ann(X_tr, y_tr, dim, out, epochs=80, bs=64, lr=0.001):
    dev = 'cuda' if torch.cuda.is_available() else 'cpu'
    Xtr, Xv, ytr, yv = train_test_split(
        X_tr, y_tr, test_size=0.15, random_state=42, stratify=y_tr
    )
    sc = StandardScaler()
    Xtr = sc.fit_transform(Xtr)
    Xv = sc.transform(Xv)
    Xtr_t = torch.FloatTensor(Xtr).to(dev)
    ytr_t = torch.LongTensor(ytr).to(dev)
    Xv_t = torch.FloatTensor(Xv).to(dev)
    loader = DataLoader(TensorDataset(Xtr_t, ytr_t),
                        batch_size=bs, shuffle=True)
    model = EmailANN(dim, out).to(dev)
    counts = np.bincount(ytr)
    w = torch.FloatTensor(
        (1.0 / counts) / (1.0 / counts).sum() * len(counts)
    ).to(dev)
    crit = nn.CrossEntropyLoss(weight=w)
    opt = optim.AdamW(model.parameters(), lr=lr, weight_decay=1e-4)
    sched = optim.lr_scheduler.ReduceLROnPlateau(opt, patience=5, factor=0.5)
    best_acc, best_st, wait = 0, None, 0
    for ep in range(epochs):
        model.train()
        for bx, by in loader:
            opt.zero_grad()
            loss = crit(model(bx), by)
            loss.backward()
            torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
            opt.step()
        model.eval()
        with torch.no_grad():
            va = accuracy_score(yv, torch.argmax(model(Xv_t), 1).cpu().numpy())
            vl = crit(model(Xv_t), torch.LongTensor(yv).to(dev)).item()
        sched.step(vl)
        if (ep + 1) % 20 == 0:
            print(f"    Ep {ep+1}: Val={va:.4f}")
        if va > best_acc:
            best_acc = va
            best_st = {k: v.cpu().clone() for k, v in model.state_dict().items()}
            wait = 0
        else:
            wait += 1
            if wait >= 10:
                print(f"    Early stop ep {ep+1}")
                break
    model.load_state_dict(best_st)
    model.to(dev)
    print(f"    Best Val: {best_acc:.4f}")
    return model, dev, sc


class ANNWrap:
    def __init__(self, dim, out):
        self.dim, self.out = dim, out
        self.model, self.dev, self.sc = None, 'cpu', None

    def fit(self, X, y):
        self.model, self.dev, self.sc = train_ann(X, y, self.dim, self.out)
        return self

    def predict(self, X):
        Xs = self.sc.transform(X) if self.sc else X
        self.model.eval()
        with torch.no_grad():
            return torch.argmax(
                self.model(torch.FloatTensor(Xs).to(self.dev)), 1
            ).cpu().numpy()


ann_l1 = ANNWrap(X_train.shape[1], 2)
ann_l2 = ANNWrap(X_train.shape[1], 2)
dl_ann = DualLayerClassifier(ann_l1, ann_l2)
dl_ann.fit(X_train, y_train)
yp = dl_ann.predict(X_test)
acc = accuracy_score(y_test, yp)
f1 = f1_score(y_test, yp, average='macro')
dl_results['DL-ANN'] = {'accuracy': acc, 'f1': f1, 'predictions': yp}
print(f"  ✅ DL-ANN: Acc={acc:.4f} | F1={f1:.4f}")

# ============================================================
# STEP 8: CROSS-VALIDATION
# ============================================================
print(f"\n{'='*70}")
print("STEP 8: CROSS-VALIDATION")
print("=" * 70)

cv = StratifiedKFold(n_splits=CONFIG['cv_folds'], shuffle=True,
                     random_state=CONFIG['random_state'])
for name in ['ExtraTrees', 'XGBoost', 'RandomForest']:
    m = sl_models[name].__class__(**sl_models[name].get_params())
    scores = cross_val_score(m, X_train, y_train, cv=cv,
                             scoring='accuracy', n_jobs=-1)
    print(f"  {name:>15}: {scores.mean():.4f} ± {scores.std():.4f}")

# ============================================================
# NON-DP SUMMARY
# ============================================================
print(f"\n{'='*70}")
print("🏆 NON-DP RESULTS")
print("=" * 70)

all_models = {}
all_models['Baseline'] = {
    'accuracy': acc_all, 'f1': f1_all, 'predictions': y_pred_all
}
for n, r in sl_results.items():
    all_models[f'SL-{n}'] = r
for n, r in dl_results.items():
    all_models[n] = r

print(f"\n{'Model':<30} {'Acc':>8} {'F1':>8} {'vs Base':>8}")
print("─" * 56)
for n, r in sorted(all_models.items(),
                   key=lambda x: x[1]['accuracy'], reverse=True):
    imp = (r['accuracy'] - acc_all) * 100
    mk = " 🏆" if r['accuracy'] == max(
        v['accuracy'] for v in all_models.values()
    ) else ""
    print(f"{n:<30} {r['accuracy']:>8.4f} {r['f1']:>8.4f} "
          f"{imp:>+7.2f}%{mk}")

best_nondp_name = max(all_models, key=lambda k: all_models[k]['accuracy'])
best_nondp_acc = all_models[best_nondp_name]['accuracy']
best_nondp_f1 = all_models[best_nondp_name]['f1']
best_nondp_preds = all_models[best_nondp_name]['predictions']

print(f"\n📊 Best: {best_nondp_name}")
print(classification_report(y_test, best_nondp_preds,
                            target_names=['Ham', 'Spam', 'Phishing']))

# ============================================================
# STEP 9: DIFFERENTIAL PRIVACY
# ============================================================
print(f"\n{'='*70}")
print("STEP 9: DIFFERENTIAL PRIVACY")
print("=" * 70)

dp_results = {}
delta = 1.0 / len(X_train)

# --- DP Logistic Regression ---
from diffprivlib.models import LogisticRegression as DPLogReg

print("\n📊 DP Logistic Regression")
for eps in [1.0, 5.0, 10.0]:
    try:
        m = DPLogReg(
            epsilon=eps,
            data_norm=np.linalg.norm(X_train, axis=1).max(),
            max_iter=200, random_state=42
        )
        m.fit(X_train, y_train)
        yp = m.predict(X_test)
        a = accuracy_score(y_test, yp)
        f = f1_score(y_test, yp, average='macro')
        dp_results[f'DP-LogReg (ε={eps})'] = {
            'epsilon': eps, 'accuracy': a, 'f1': f,
            'model_type': 'LogReg', 'predictions': yp
        }
        print(f"  ε={eps}: Acc={a:.4f}")
    except Exception as e:
        print(f"  ε={eps}: Error: {str(e)[:60]}")

# --- DP-ANN ---
print("\n📊 DP-ANN (Opacus)")


class DPEmailANN(nn.Module):
    def __init__(self, dim, out, drop=0.2):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(dim, 512), nn.GroupNorm(8, 512),
            nn.ReLU(), nn.Dropout(drop),
            nn.Linear(512, 256), nn.GroupNorm(8, 256),
            nn.ReLU(), nn.Dropout(drop),
            nn.Linear(256, 128), nn.GroupNorm(8, 128),
            nn.ReLU(), nn.Dropout(drop * 0.5),
            nn.Linear(128, out))

    def forward(self, x):
        return self.net(x)


def train_dp_ann(X_tr, y_tr, dim, out, target_eps, delta=1e-5,
                 epochs=20, bs=256, lr=0.002):
    dev = 'cuda' if torch.cuda.is_available() else 'cpu'
    Xtr, Xv, ytr, yv = train_test_split(
        X_tr, y_tr, test_size=0.1, random_state=42, stratify=y_tr
    )
    sc = StandardScaler()
    Xtr = sc.fit_transform(Xtr)
    Xv = sc.transform(Xv)
    loader = DataLoader(
        TensorDataset(torch.FloatTensor(Xtr), torch.LongTensor(ytr)),
        batch_size=bs, shuffle=True, drop_last=True
    )
    Xv_t = torch.FloatTensor(Xv).to(dev)
    model = ModuleValidator.fix(DPEmailANN(dim, out).to(dev))
    counts = np.bincount(ytr)
    w = torch.FloatTensor(
        (1.0 / counts) / (1.0 / counts).sum() * len(counts)
    ).to(dev)
    crit = nn.CrossEntropyLoss(weight=w)
    opt = optim.Adam(model.parameters(), lr=lr)
    pe = PrivacyEngine()
    model, opt, loader = pe.make_private_with_epsilon(
        module=model, optimizer=opt, data_loader=loader,
        epochs=epochs, target_epsilon=target_eps,
        target_delta=delta, max_grad_norm=1.0
    )
    print(f"    Noise: {opt.noise_multiplier:.3f}")
    best_acc, best_st = 0, None
    for ep in range(epochs):
        model.train()
        for bx, by in loader:
            bx, by = bx.to(dev), by.to(dev)
            opt.zero_grad()
            loss = crit(model(bx), by)
            loss.backward()
            opt.step()
        model.eval()
        with torch.no_grad():
            va = accuracy_score(
                yv, torch.argmax(model(Xv_t), 1).cpu().numpy()
            )
        cur_eps = pe.get_epsilon(delta=delta)
        if (ep + 1) % 10 == 0:
            print(f"    Ep {ep+1}: Val={va:.4f} | ε={cur_eps:.2f}")
        if va > best_acc:
            best_acc = va
            best_st = {
                k: v.cpu().clone() for k, v in model.state_dict().items()
            }
    final_eps = pe.get_epsilon(delta=delta)
    print(f"    Final ε={final_eps:.2f} | Best Val={best_acc:.4f}")
    model.load_state_dict(best_st)
    model.to(dev)
    return model, dev, sc, final_eps


class DPANNWrap:
    def __init__(self, dim, out, eps=1.0, delta=1e-5):
        self.dim, self.out, self.eps, self.delta = dim, out, eps, delta
        self.model, self.dev, self.sc, self.actual_eps = None, 'cpu', None, None

    def fit(self, X, y):
        self.model, self.dev, self.sc, self.actual_eps = train_dp_ann(
            X, y, self.dim, self.out, self.eps, self.delta
        )
        return self

    def predict(self, X):
        Xs = self.sc.transform(X) if self.sc else X
        self.model.eval()
        with torch.no_grad():
            return torch.argmax(
                self.model(torch.FloatTensor(Xs).to(self.dev)), 1
            ).cpu().numpy()


for eps in [1.0, 2.0, 5.0, 10.0]:
    print(f"\n  ── DP-ANN (ε={eps}) ──")
    try:
        wrap = DPANNWrap(X_train.shape[1], 3, eps, delta)
        wrap.fit(X_train, y_train)
        yp = wrap.predict(X_test)
        a = accuracy_score(y_test, yp)
        f = f1_score(y_test, yp, average='macro')
        dp_results[f'DP-ANN (ε={eps})'] = {
            'epsilon': eps, 'accuracy': a, 'f1': f,
            'model_type': 'DP-ANN', 'predictions': yp
        }
        print(f"  ✅ Acc={a:.4f} | F1={f:.4f}")
    except Exception as e:
        print(f"  ❌ {str(e)[:100]}")

# --- DP Dual-Layer ANN ---
print(f"\n📊 DP Dual-Layer ANN")


class DPDualLayerClassifier:
    def __init__(self, l1, l2, e1=1.0, e2=1.0):
        self.l1, self.l2 = l1, l2
        self.e1, self.e2, self.total = e1, e2, e1 + e2

    def fit(self, X, y):
        y1 = np.where(y == 2, 1, 0)
        print(f"    L1(ε={self.e1}): P={np.sum(y1==1)}, H={np.sum(y1==0)}")
        self.l1.fit(X, y1)
        m = (y != 2)
        print(f"    L2(ε={self.e2}): Ham={np.sum(y[m]==0)}, "
              f"Spam={np.sum(y[m]==1)}")
        self.l2.fit(X[m], y[m])
        print(f"    Total ε={self.total}")
        return self

    def predict(self, X):
        f = np.zeros(len(X), dtype=int)
        p = self.l1.predict(X)
        f[p == 1] = 2
        h = (p == 0)
        if np.any(h):
            f[h] = self.l2.predict(X[h])
        return f


for total_eps in [2.0, 5.0, 10.0]:
    epl = total_eps / 2.0
    print(f"\n  ── DL-DP-ANN (total ε={total_eps}) ──")
    try:
        l1 = DPANNWrap(X_train.shape[1], 2, epl, delta)
        l2 = DPANNWrap(X_train.shape[1], 2, epl, delta)
        dl = DPDualLayerClassifier(l1, l2, epl, epl)
        dl.fit(X_train, y_train)
        yp = dl.predict(X_test)
        a = accuracy_score(y_test, yp)
        f = f1_score(y_test, yp, average='macro')
        dp_results[f'DL-DP-ANN (ε={total_eps})'] = {
            'epsilon': total_eps, 'accuracy': a, 'f1': f,
            'model_type': 'DL-DP-ANN', 'predictions': yp
        }
        print(f"  ✅ Acc={a:.4f} | F1={f:.4f}")
    except Exception as e:
        print(f"  ❌ {str(e)[:100]}")

# ============================================================
# STEP 10: IMPROVED DP STRATEGIES
# ============================================================
print(f"\n{'='*70}")
print("STEP 10: IMPROVED DP STRATEGIES")
print("=" * 70)

# --- PCA ---
print("\n📊 PCA: 3000 → 500 dimensions")
pca = PCA(n_components=500, random_state=42)
X_train_pca = pca.fit_transform(X_train)
X_test_pca = pca.transform(X_test)
print(f"   Variance retained: {pca.explained_variance_ratio_.sum()*100:.1f}%")

# --- Improved DP-ANN ---


class ImprovedDPANN(nn.Module):
    def __init__(self, dim, out):
        super().__init__()
        self.fc1 = nn.Linear(dim, 1024)
        self.gn1 = nn.GroupNorm(16, 1024)
        self.fc2 = nn.Linear(1024, 1024)
        self.gn2 = nn.GroupNorm(16, 1024)
        self.fc3 = nn.Linear(1024, 512)
        self.gn3 = nn.GroupNorm(16, 512)
        self.fc_out = nn.Linear(512, out)
        self.relu = nn.ReLU()
        self.drop = nn.Dropout(0.1)

    def forward(self, x):
        h1 = self.drop(self.relu(self.gn1(self.fc1(x))))
        h2 = self.drop(self.relu(self.gn2(self.fc2(h1))))
        h2 = h2 + h1
        h3 = self.drop(self.relu(self.gn3(self.fc3(h2))))
        return self.fc_out(h3)


def train_improved_dp(X_tr, y_tr, dim, out, eps, delta=1e-5,
                      epochs=20, bs=512, lr=0.003):
    dev = 'cuda' if torch.cuda.is_available() else 'cpu'
    Xtr, Xv, ytr, yv = train_test_split(
        X_tr, y_tr, test_size=0.1, random_state=42, stratify=y_tr
    )
    sc = StandardScaler()
    Xtr = sc.fit_transform(Xtr)
    Xv = sc.transform(Xv)
    loader = DataLoader(
        TensorDataset(torch.FloatTensor(Xtr), torch.LongTensor(ytr)),
        batch_size=bs, shuffle=True, drop_last=True
    )
    Xv_t = torch.FloatTensor(Xv).to(dev)
    model = ModuleValidator.fix(ImprovedDPANN(dim, out).to(dev))
    counts = np.bincount(ytr)
    w = torch.FloatTensor(
        (1.0 / counts) / (1.0 / counts).sum() * len(counts)
    ).to(dev)
    crit = nn.CrossEntropyLoss(weight=w)
    opt = optim.Adam(model.parameters(), lr=lr)
    pe = PrivacyEngine()
    model, opt, loader = pe.make_private_with_epsilon(
        module=model, optimizer=opt, data_loader=loader,
        epochs=epochs, target_epsilon=eps,
        target_delta=delta, max_grad_norm=1.2
    )
    print(f"    Noise={opt.noise_multiplier:.3f} bs={bs}")
    best_acc, best_st = 0, None
    for ep in range(epochs):
        model.train()
        for bx, by in loader:
            bx, by = bx.to(dev), by.to(dev)
            opt.zero_grad()
            loss = crit(model(bx), by)
            loss.backward()
            opt.step()
        model.eval()
        with torch.no_grad():
            va = accuracy_score(
                yv, torch.argmax(model(Xv_t), 1).cpu().numpy()
            )
        if (ep + 1) % 5 == 0:
            print(f"    Ep {ep+1}: Val={va:.4f} ε={pe.get_epsilon(delta):.2f}")
        if va > best_acc:
            best_acc = va
            best_st = {
                k: v.cpu().clone() for k, v in model.state_dict().items()
            }
    model.load_state_dict(best_st)
    model.to(dev)
    print(f"    Best Val={best_acc:.4f}")
    return model, dev, sc


# Strategy A: PCA + Improved DP-ANN
print("\n📊 Strategy A: PCA + Improved DP-ANN")
for eps in [1.0, 2.0, 5.0, 10.0]:
    print(f"\n  ── PCA+IDP (ε={eps}) ──")
    try:
        model, dev, sc = train_improved_dp(
            X_train_pca, y_train, 500, 3, eps, delta
        )
        Xs = sc.transform(X_test_pca)
        model.eval()
        with torch.no_grad():
            yp = torch.argmax(
                model(torch.FloatTensor(Xs).to(dev)), 1
            ).cpu().numpy()
        a = accuracy_score(y_test, yp)
        f = f1_score(y_test, yp, average='macro')
        dp_results[f'PCA+IDP (ε={eps})'] = {
            'epsilon': eps, 'accuracy': a, 'f1': f,
            'model_type': 'PCA+IDP', 'predictions': yp
        }
        print(f"  ✅ Acc={a:.4f} | F1={f:.4f}")
    except Exception as e:
        print(f"  ❌ {str(e)[:80]}")


# Strategy B: PATE
print(f"\n📊 Strategy B: PATE (Teacher Ensembles)")


class PATE:
    def __init__(self, n_teachers=30, noise=1.0):
        self.n_teachers = n_teachers
        self.noise = noise
        self.teachers = []

    def fit(self, X, y):
        n = len(X)
        idx = np.random.RandomState(42).permutation(n)
        ps = n // self.n_teachers
        for i in range(self.n_teachers):
            s_idx = i * ps
            e_idx = (i + 1) * ps if i < self.n_teachers - 1 else n
            t = ExtraTreesClassifier(
                n_estimators=100, random_state=42 + i, n_jobs=-1
            )
            t.fit(X[idx[s_idx:e_idx]], y[idx[s_idx:e_idx]])
            self.teachers.append(t)
            if (i + 1) % 10 == 0:
                print(f"    Teacher {i+1}/{self.n_teachers}")
        return self

    def predict(self, X):
        votes = np.zeros((len(X), 3))
        for t in self.teachers:
            p = t.predict(X)
            for i in range(len(X)):
                votes[i, p[i]] += 1
        votes += np.random.laplace(0, self.noise, votes.shape)
        return np.argmax(votes, axis=1)

    def approx_eps(self, n_queries):
        return 2.0 * n_queries / (self.noise * self.n_teachers)


pate_base = PATE(n_teachers=30, noise=1.0)
pate_base.fit(X_train, y_train)  # fit teachers ONCE — noise only affects predict()

for noise in [0.5, 1.0, 2.0]:
    print(f"\n  ── PATE (noise={noise}) ──")
    pate = pate_base
    pate.noise = noise
    yp = pate.predict(X_test)
    a = accuracy_score(y_test, yp)
    f = f1_score(y_test, yp, average='macro')
    eps_approx = pate.approx_eps(len(X_test))
    dp_results[f'PATE (noise={noise})'] = {
        'epsilon': eps_approx, 'accuracy': a, 'f1': f,
        'model_type': 'PATE', 'predictions': yp
    }
    print(f"  ✅ Acc={a:.4f} | F1={f:.4f} | ≈ε={eps_approx:.1f}")

# Strategy C: DP Ensemble
print(f"\n📊 Strategy C: DP Ensemble")
for eps in [5.0, 10.0]:
    print(f"\n  ── DP-Ensemble (ε={eps}) ──")
    probas = []
    for i in range(3):
        print(f"    Model {i+1}/3:")
        try:
            model, dev, sc = train_improved_dp(
                X_train_pca, y_train, 500, 3, eps, delta,
                epochs=15, bs=512
            )
            Xs = sc.transform(X_test_pca)
            model.eval()
            with torch.no_grad():
                logits = model(torch.FloatTensor(Xs).to(dev))
                probas.append(
                    torch.softmax(logits, dim=1).cpu().numpy()
                )
        except Exception as e:
            print(f"    ❌ {str(e)[:60]}")
    if probas:
        yp = np.argmax(np.mean(probas, axis=0), axis=1)
        a = accuracy_score(y_test, yp)
        f = f1_score(y_test, yp, average='macro')
        dp_results[f'DP-Ensemble (ε={eps})'] = {
            'epsilon': eps, 'accuracy': a, 'f1': f,
            'model_type': 'DP-Ensemble', 'predictions': yp
        }
        print(f"  ✅ Ensemble: Acc={a:.4f} | F1={f:.4f}")

# ============================================================
# COMPLETE RESULTS
# ============================================================
print(f"\n{'='*70}")
print("🏆 COMPLETE RESULTS: NON-DP vs DP")
print("=" * 70)

print(f"\n{'Model':<40} {'Acc':>8} {'F1':>8} {'ε':>8} {'Gap':>8}")
print("─" * 72)
print(f"{'[REF] ' + best_nondp_name:<40} "
      f"{best_nondp_acc:>8.4f} {best_nondp_f1:>8.4f} {'∞':>8} {'---':>8}")
print("─" * 72)

sorted_dp = sorted(dp_results.items(),
                   key=lambda x: x[1]['accuracy'], reverse=True)

for name, r in sorted_dp:
    gap = (best_nondp_acc - r['accuracy']) * 100
    eps_str = f"{r['epsilon']:.1f}" if r['epsilon'] < 100 else f"{r['epsilon']:.0f}"
    mk = " 🏆" if name == sorted_dp[0][0] else ""
    print(f"{name:<40} {r['accuracy']:>8.4f} {r['f1']:>8.4f} "
          f"{eps_str:>8} {gap:>7.2f}%{mk}")

best_dp_name = sorted_dp[0][0]
best_dp = sorted_dp[0][1]

print(f"\n🏆 Best DP: {best_dp_name}")
print(f"   Accuracy: {best_dp['accuracy']:.4f} "
      f"({best_dp['accuracy']*100:.2f}%)")
print(f"   Gap to Non-DP: "
      f"{(best_nondp_acc - best_dp['accuracy'])*100:.2f}%")
print(classification_report(
    y_test, best_dp['predictions'],
    target_names=['Ham', 'Spam', 'Phishing']
))

# ============================================================
# VISUALIZATIONS
# ============================================================
print(f"\n{'='*70}")
print("VISUALIZATIONS")
print("=" * 70)

# Plot 1: Bar chart comparison
fig, ax = plt.subplots(figsize=(16, 7))
bars_data = {'Non-DP\nBest': best_nondp_acc}
for name, r in sorted_dp[:6]:
    short = name[:22]
    bars_data[short] = r['accuracy']

colors_bar = ['#2ecc71'] + ['#3498db'] * 6
bars = ax.bar(range(len(bars_data)),
              [v * 100 for v in bars_data.values()],
              color=colors_bar[:len(bars_data)], width=0.6,
              edgecolor='black', linewidth=0.5)
ax.set_xticks(range(len(bars_data)))
ax.set_xticklabels(bars_data.keys(), fontsize=9, rotation=20, ha='right')
ax.set_ylabel('Accuracy (%)', fontsize=12)
ax.set_title('Non-DP vs DP (All Strategies)',
             fontsize=14, fontweight='bold')
for bar in bars:
    h = bar.get_height()
    ax.text(bar.get_x() + bar.get_width() / 2., h + 0.3,
            f'{h:.2f}%', ha='center', fontweight='bold', fontsize=10)
ax.set_ylim(40, 105)
ax.grid(axis='y', alpha=0.3)
ax.legend(handles=[
    Patch(color='#2ecc71', label='Non-DP'),
    Patch(color='#3498db', label='DP'),
], fontsize=10)
plt.tight_layout()
plt.savefig('final_comparison.png', dpi=150)
plt.show()
print("✅ final_comparison.png")

# Plot 2: Confusion matrices
fig2, axes = plt.subplots(1, 2, figsize=(14, 6))
cm1 = confusion_matrix(y_test, best_nondp_preds)
sns.heatmap(cm1, annot=True, fmt='d', cmap='Blues',
            xticklabels=['Ham', 'Spam', 'Phish'],
            yticklabels=['Ham', 'Spam', 'Phish'], ax=axes[0])
axes[0].set_title(f'Non-DP Best\n{best_nondp_acc:.4f}', fontweight='bold')
axes[0].set_ylabel('True')
axes[0].set_xlabel('Predicted')

cm2 = confusion_matrix(y_test, best_dp['predictions'])
sns.heatmap(cm2, annot=True, fmt='d', cmap='Greens',
            xticklabels=['Ham', 'Spam', 'Phish'],
            yticklabels=['Ham', 'Spam', 'Phish'], ax=axes[1])
axes[1].set_title(f'Best DP\n{best_dp["accuracy"]:.4f}', fontweight='bold')
axes[1].set_ylabel('True')
axes[1].set_xlabel('Predicted')

plt.suptitle('Non-DP vs Best DP', fontweight='bold')
plt.tight_layout()
plt.savefig('final_confusion.png', dpi=150)
plt.show()
print("✅ final_confusion.png")

# Plot 3: Privacy-utility curve
fig3, ax = plt.subplots(figsize=(14, 7))
strategy_colors = {
    'PCA+IDP': '#3498db', 'PATE': '#e74c3c',
    'DP-Ensemble': '#9b59b6', 'DP-ANN': '#e67e22',
    'DL-DP-ANN': '#1abc9c', 'LogReg': '#95a5a6',
}
for mt in set(r['model_type'] for r in dp_results.values()):
    mr = sorted(
        [v for v in dp_results.values() if v['model_type'] == mt],
        key=lambda x: x['epsilon']
    )
    if len(mr) >= 2:
        ax.plot(
            [r['epsilon'] for r in mr],
            [r['accuracy'] for r in mr],
            'o-', label=mt,
            color=strategy_colors.get(mt, '#333'),
            linewidth=2, markersize=8
        )
ax.axhline(y=best_nondp_acc, color='red', linestyle='--',
           alpha=0.7, label=f'Non-DP ({best_nondp_acc:.4f})')
ax.set_xlabel('Privacy Budget (ε)', fontsize=12)
ax.set_ylabel('Accuracy', fontsize=12)
ax.set_title('Privacy-Utility Tradeoff — All Strategies',
             fontsize=14, fontweight='bold')
ax.legend(fontsize=9, loc='lower right')
ax.grid(True, alpha=0.3)
ax.set_xscale('log')
plt.tight_layout()
plt.savefig('final_privacy_utility.png', dpi=150)
plt.show()
print("✅ final_privacy_utility.png")

# ============================================================
# FINAL SUMMARY
# ============================================================
print(f"\n{'='*70}")
print("🏆 FINAL SUMMARY")
print("=" * 70)

print(f"""
📊 RESULTS:
   Baseline:              {acc_all*100:.2f}%
   Best Non-DP:           {best_nondp_acc*100:.2f}% ({best_nondp_name})
   Best DP:               {best_dp['accuracy']*100:.2f}% ({best_dp_name})
   Gap to Non-DP:         {(best_nondp_acc - best_dp['accuracy'])*100:.2f}%

🔧 FIXES APPLIED:
   ✅ No data leakage (TF-IDF, Scaler, SelectKBest on train only)
   ✅ Feature ranking on training data only
   ✅ XGBoost eval_metric corrected (logloss for binary)
   ✅ Cross-validation added
   ✅ Centralized CONFIG

🔒 DP STRATEGIES:
   ✅ DP Logistic Regression (diffprivlib)
   ✅ DP-ANN with Opacus (DP-SGD)
   ✅ DP Dual-Layer ANN
   ✅ PCA + Improved DP-ANN (reduced dimensions)
   ✅ PATE Teacher Ensembles
   ✅ DP Ensemble Voting

📁 SAVED PLOTS:
   • final_comparison.png
   • final_confusion.png
   • final_privacy_utility.png
""")

print("=" * 70)
print("✅ COMPLETE PIPELINE DONE")
print("=" * 70)